<?php
if($this->session->has('mhs')){
    $id = $this->session->get('id');
    ?>
    <h3>Daftar Inventaris</h3>
    <table class="table table-bordered table-hover">
        <thead class="thead-light">
            <tr>
                <th>Nomor</th>
                <th>Nama</th>
                <th>Status</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($invens as $inven) { ?>
            <tr>
                <td><?php echo $inven->id_inv; ?></td>
                <td><?php echo $inven->nama_inv; ?></td>
                <td><?php echo $inven->status_inv; ?></td>
                <td>
                    <?php
                        echo $this->tag->linkTo([
                            "/mahasiswa/createInv/". implode("",$id) . "/" . $inven->id_inv,
                            "Request",
                        ]);
                    ?>
                </td>
            </tr>
        <?php } ?>
        </tbody>
    </table>
    <div>
    <?php
        echo $this->tag->linkTo([
            "/mahasiswa/". implode("",$id),
            "Kembali",
        ]);
    ?>
    </div> 
    <?php
}