<h2>Sign up using this form</h2>

<?php echo $this->tag->form("signup/register"); ?>
    
    <p>
        <label for="nama">Nama</label>
        <?php echo $this->tag->textField("nama"); ?>
    </p>

    <p>
        <label for="nrp">NRP</label>
        <?php echo $this->tag->textField("nrp"); ?>
    </p>

    <p>
        <label for="no_telp">Nomor Telepon</label>
        <?php echo $this->tag->textField("no_telp"); ?>
    </p>

    <p>
        <label for="alamat">Alamat</label>
        <?php echo $this->tag->textField("alamat"); ?>
    </p>

    <p>
        <label for="password">Password</label>
        <?php echo $this->tag->passwordField("password"); ?>
    </p>

    <p>
        <?php echo $this->tag->submitButton("Register"); ?>
    </p>

</form>