<?php
if ($this->session->has('isAdmin')) {
    $name = $this->session->get('nama');
    $id = $this->session->get('isAdmin');
    echo implode("",$name) . " ";
    echo $this->tag->linkTo([
        "/pengguna/logout",
        "Logout",
    ]);
    ?>
    <div>
        <?php
            echo $this->tag->linkTo([
                "/admin/".implode("",$id)."/createInv",
                "Tambah Inventaris",
            ]);
        ?>
    </div>
    <div>
        <?php
            echo $this->tag->linkTo([
                "/admin/".implode("",$id)."/listInv",
                "Daftar Inventaris",
            ]);
        ?>
    </div>
    <table class="table table-bordered table-hover">
    <thead class="thead-light">
        <tr>
            <th>Nomor</th>
            <th>Nama</th>
            <th>Nama Barang</th>
            <th>Status</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
    <?php
    if ($pinjInvs->count() > 0) {
        foreach ($pinjInvs as $pinjInv) { ?>
        <tr>
            <td><?php echo $pinjInv->id; ?></td>
            <td><?php echo $pinjInv->nama; ?></td>
            <td><?php echo $pinjInv->nama_barang; ?></td>
            <td><?php echo $pinjInv->status; ?></td>
            <td>
                <?php
                    echo $this->tag->linkTo([
                        "/admin/".implode("",$id)."/confirmInv/".$pinjInv->id,
                        "Konfirmasi",
                    ]);
                    echo $this->tag->linkTo([
                        "/admin/".implode("",$id)."/declineInv/".$pinjInv->id,
                        "Tolak",
                    ]);
                ?>
            </td>
        </tr>
    <?php } 
    }else{ 
        ?>
        <tr>
            <td colspan="5"><p class="text-center">Bersiihh, tidak ada request barang~</p></td>
        </tr>
        <?php
    } ?>
    </tbody>
</table>
<?php
}else{
    echo "Sorii, hanya admin yang boleh mengakses halaman ini :)";
    header( "refresh:2;url=/" );
}