<?php
if ($this->session->has('isAdmin')) {
    $name = $this->session->get('nama');
    $id = implode("",$this->session->get('isAdmin'));
    ?>
    <h3>Barang Pinjaman</h3>
    <table class="table table-bordered table-hover">
    <thead class="thead-light">
        <tr class="text-center">
            <th>Nomor</th>
            <th>Nama</th>
            <th>Nama Barang</th>
            <th>Status</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
    <?php
    if ($pinjInvs->count() > 0) {
        foreach ($pinjInvs as $pinjInv) { ?>
        <tr>
            <td class="counterCell"></td>
            <td><?php echo $pinjInv->nama; ?></td>
            <td><?php echo $pinjInv->nama_barang; ?></td>
            <td><?php echo $pinjInv->status; ?></td>
            <td>
                <div class="d-flex justify-content-around">
                    <?php
                        echo $this->tag->linkTo([
                            "/admin/".$id."/confirmInv/".$pinjInv->id,
                            "Konfirmasi",
                            'class' => 'btn btn-success',
                            'style' => 'width:110px'
                        ]);
                        echo $this->tag->linkTo([
                            "/admin/".$id."/declineInv/".$pinjInv->id,
                            "Tolak",
                            'class' => 'btn btn-danger',
                            'style' => 'width:110px'
                        ]);
                    ?>
                </div>
            </td>
        </tr>
    <?php } 
    }else{ 
        ?>
        <tr>
            <td colspan="5"><p class="text-center">Bersiihh, tidak ada request barang~</p></td>
        </tr>
        <?php
    } ?>
    </tbody>
</table>
<?php
}else{
    echo "Sorii, hanya admin yang boleh mengakses halaman ini :)";
    header( "refresh:2;url=/" );
}