<div style="margin-top: 8%">
    <div class="text-center">
        <div class="page-header">
            <img src="img/Lammas_Logo.png" style="width: 200px">
            <h1>Welcome to Lammas</h1>
        </div>

        <p>Already have an account? Login below!</p>
        
        <div class="container" style="width: 300px">
            <?php
            echo $this->tag->linkTo([
                "/login",
                "Login!", 
                'class' => 'btn btn-primary btn-lg btn-block'
            ]);?>
        </div>
        
        <p>Don't have one? <?php echo $this->tag->linkTo("signup", "Sign Up Here!");?></p>
    </div>
</div>