<?php
if ($this->session->has('isAdmin')) {
    $id = implode("",$this->session->get('isAdmin'))
    ?>
    <h3 style = "padding-bottom : 30px">Menambah Inventaris</h3>

    <?php echo $this->tag->form("inventaris/submit/".$id); ?>
        
        <p>
            <label for="nama" style="width: 150px">Nama</label>
            <?php echo $this->tag->textField("nama"); ?>
        </p>
        <p>
            <label for="status" style="width: 150px">Status</label>
            <?php echo $this->tag->textField("status"); ?>
        </p>
        <div class="d-flex justify-content-between" style="padding-top : 200px">
            <?php echo $this->tag->linkTo(
                [
                    "/admin/".$id,
                    "Kembali",
                    'class' => 'btn btn-primary',
                ]); ?>
            <?php echo $this->tag->submitButton(
                [
                    "Submit",
                    'class' => 'btn btn-success',
                ]); ?>
        </div>

    </form>
<?php 
}else{
    echo "Sorii, hanya admin yang boleh mengakses halaman ini :)";
    header( "refresh:2;url=/" );
}

?>