<?php
if ($this->session->has('isAdmin')) {
    $id = $this->session->get('isAdmin')
    ?>
    <h2>Menambah Inventaris</h2>

    <?php echo $this->tag->form("inventaris/submit/".implode("",$id)); ?>
        
        <p>
            <label for="nama">Nama</label>
            <?php echo $this->tag->textField("nama"); ?>
        </p>
        <p>
            <label for="status">Status</label>
            <?php echo $this->tag->textField("status"); ?>
        </p>
        <p>
            <?php echo $this->tag->submitButton("Submit"); ?>
        </p>

    </form>
    <div>
    <?php
        echo $this->tag->linkTo([
            "/admin/".implode("",$id),
            "Kembali",
        ]);
    ?>
</div>
<?php 
}else{
    echo "Sorii, hanya admin yang boleh mengakses halaman ini :)";
    header( "refresh:2;url=/" );
}

?>