<?php
if ($this->session->has('isAdmin')) {
    ?>
    <h2>Edit Inventaris</h2>

    <?php echo $this->tag->form("inventaris/edit/".$invenId); ?>
        
        <p>
            <label for="nama">Nama</label>
            <?php echo $this->tag->textField(['nama', 'value' => $nama]); ?>
        </p>

        <p>
            <label for="status">Status</label>
            <?php echo $this->tag->textField(['status', 'value' => $status]); ?>
        </p>

        <p>
            <?php echo $this->tag->submitButton("Submit"); ?>
        </p>

    </form>
<?php
}else{
    echo "Sorii, hanya admin yang boleh mengakses halaman ini :)";
    header( "refresh:2;url=/" );
}
?>