<?php
if ($this->session->has('mhs')) {
    ?>
    <h2>Edit Inventaris</h2>

    <?php echo $this->tag->form("inventaris/request/".$id."/".$invenId); ?>
        
        <p>
            <label for="nama">Nama</label>
            <?php echo $this->tag->textField(['nama', 'value' => $nama]); ?>
        </p>

        <p>
            <label for="status">Keperluan</label>
            <?php echo $this->tag->textField('keperluan'); ?>
        </p>

        <p>
            <label for="tanggal">Tanggal Pinjam</label>
            <?php echo $this->tag->dateField('tanggal'); ?>
        </p>

        <p>
            <?php echo $this->tag->submitButton("Submit"); ?>
        </p>

    </form>
    <div>
    <?php
        echo $this->tag->linkTo([
            "/mahasiswa/".$id."/requestInv",
            "Kembali",
        ]);
    ?>
    </div>  
<?php
}else{
    echo "Sorii, hanya admin yang boleh mengakses halaman ini :)";
    header( "refresh:2;url=/" );
}
?>